name: "run test"

runs:
  using: composite
  steps:
    - name: Set up swap space
      if: runner.os == 'Linux'
      uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: 10

    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
        cache: pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build packages, examples and comparisons
      run: pnpm build

    - name: Test packages
      run: pnpm test

    - name: Lint and format packages
      run: pnpm format

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.2.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
