stateDiagram-v2
	[*] --> Off: Reset (initialCounter=0)

	Off --> OffGate: Switch
	state OffGate <<choice>>
	OffGate --> Red: isEqual(#correlationId, $targetId)
	OffGate --> Off

	Red --> RedGate: Switch
	state RedGate <<choice>>
	RedGate --> RedYellow: isEqual(#correlationId, $targetId)
	RedGate --> Red

	Red --> RedResetGate: Reset
	state RedResetGate <<choice>>
	RedResetGate --> Off: isEqual(#correlationId, $targetId)
	RedResetGate --> Red

	RedYellow --> RedYellowGate: Switch
	state RedYellowGate <<choice>>
	RedYellowGate --> Green: isEqual(#correlationId, $targetId)
	RedYellowGate --> RedYellow

	RedYellow --> RedYellowResetGate: Reset
	state RedYellowResetGate <<choice>>
	RedYellowResetGate --> Off: isEqual(#correlationId, $targetId)
	RedYellowResetGate --> RedYellow

	Green --> GreenGate: Switch
	state GreenGate <<choice>>
	GreenGate --> Yellow: isEqual(#correlationId, $targetId)
	GreenGate --> Green

	Green --> GreenResetGate: Reset
	state GreenResetGate <<choice>>
	GreenResetGate --> Off: isEqual(#correlationId, $targetId)
	GreenResetGate --> Green

	Yellow --> YellowGate: Switch
	state YellowGate <<choice>>
	YellowGate --> Red: isEqual(#correlationId, $targetId)
	YellowGate --> Yellow

	Yellow --> YellowResetGate: Reset
	state YellowResetGate <<choice>>
	YellowResetGate --> Off: isEqual(#correlationId, $targetId)
	YellowResetGate --> Yellow

note right of [*]
#{correlationId} <= coalesce(#correlationId, '')
#{counter} <= if(and(not(isNull($initialCounter)), isEqual(#correlationId, $targetId)), $initialCounter, coalesce(#counter, 0))
define/incIfMatch (count, myId, tid) => if(and(not(isNull(tid)), isEqual(myId, tid)), inc(count), count)
end note

note left of Off
+Init
#{correlationId} <= coalesce(#correlationId, '')
#{counter} <= coalesce(#counter, 0)
subscribe/SWITCH Switch ($targetId) <= ($id)
subscribe/RESET Reset ($targetId, $initialCounter) <= ($id, $initialCounter)
end note

note right of Red
#{correlationId} <= coalesce(#correlationId, '')
#{counter} <= incIfMatch(#counter, #correlationId, $targetId)
end note

note left of RedYellow
#{correlationId} <= coalesce(#correlationId, '')
#{counter} <= incIfMatch(#counter, #correlationId, $targetId)
end note

note right of Green
#{correlationId} <= coalesce(#correlationId, '')
#{counter} <= incIfMatch(#counter, #correlationId, $targetId)
end note

note left of Yellow
#{correlationId} <= coalesce(#correlationId, '')
#{counter} <= incIfMatch(#counter, #correlationId, $targetId)
end note
