name: 🧩 Strategic task
description: Implementation by core team
labels: ['strategic']
projects: ['tfcp68/3']
body:
  - type: markdown
    attributes:
      value: 
        This form is meant for project supervizors and creates a milestone task in the roadmap. 
        _It's advised to create a branch and document the feature first_
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: 'What has to be done, i.e. a certain functionality'
    validations:
      required: true
  - type: textarea
    id: feature-details
    attributes:
      label: Definition of done
      description: 'Technical details of what has to be implemented'
    validations:
      required: true
  - type: textarea
    id: additional-references
    attributes:
      label: Additional references
      description: Any useful links and references
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/tfcp68/yantrix/issues) that request the same feature to avoid creating a duplicate.
          required: true
