import { TStaticMethods } from '@yantrix/core';
import { hasCycle, isAutomata, isAutomataInstance, isPropsUseFSM } from './typeGuards';
import { TUseFSMInput } from './types';

export const isNullish = (v: unknown): v is null | undefined => v === null || v === undefined;

/**
 * Return a shallow, value-object copy of the Automata class "static side".
 * It includes codegen helpers (e.g., getState/getAction) when passed either:
 * - a class constructor with statics
 * - a props object { Automata: ctor, id }
 * - a props object { Automata: instance, id } - in this case statics are taken from instance.constructor
 */
export const setInitialStaticMethods = (Automata: TUseFSMInput): TStaticMethods => {
	// From class constructor generated by codegen
	if (isAutomata(Automata)) {
		return Automata;
	}

	// From props { Automata, id }
	if (isPropsUseFSM(Automata)) {
		const props = Automata;

		// If Automata is a class constructor, just return its statics
		if (typeof props.Automata === 'function') {
			return props.Automata;
		}

		// If Automata is an instance, read statics from its constructor
		if (isAutomataInstance(props.Automata)) {
			return props.Automata;
		}
	}

	throw new Error('Unsupported Automata input for setInitialStaticMethods');
};

/**
 * Read the "version" of the FSM. Version increments with each transition.
 */
export function readVersion<Selection>(fsmStore: Selection): number {
	if (hasCycle(fsmStore)) {
		return fsmStore.currentCycle;
	}

	return 0;
}
