import { TStaticMethods } from '@yantrix/core';
import { hasCycle, isAutomata, isAutomataInstance, isPropsUseFSM } from './typeGuards';
import { TUseFSMInput } from './types';

export const isNullish = (v: unknown): v is null | undefined => v === null || v === undefined;

/**
 * Returns the Automata "static side" (codegen helpers like getState/getAction).
 *
 * Supported inputs:
 * - An Automata class constructor that includes statics (codegen output)
 * - A props object { Automata: ctor, id }
 * - A props object { Automata: instance, id }
 */
export const setInitialStaticMethods = (Automata: TUseFSMInput): TStaticMethods => {
	// From class constructor generated by codegen
	if (isAutomata(Automata)) {
		return Automata;
	}

	// From props { Automata, id }
	if (isPropsUseFSM(Automata)) {
		const props = Automata;

		// If Automata is a class constructor, just return its statics
		if (typeof props.Automata === 'function') {
			return props.Automata;
		}

		// If Automata is an instance, read statics from its constructor
		if (isAutomataInstance(props.Automata)) {
			return props.Automata;
		}
	}

	throw new Error('Unsupported Automata input for setInitialStaticMethods');
};

/**
 * Read the "version" of the FSM. Version increments with each transition.
 */
export function readVersion<Selection>(fsmStore: Selection): number {
	if (hasCycle(fsmStore)) {
		return fsmStore.currentCycle;
	}

	return 0;
}
