stateDiagram-v2
	direction LR

	[*] --> Configuring: Init

	Configuring --> Configuring: UpdateInput
	Configuring --> Ticking: Apply

	Ticking --> TickProcess: Tick
	TickProcess --> Ticking: [-]

	Ticking --> Paused: Stop
	Paused --> Ticking: Start

	Configuring --> Configuring: Reset
	Ticking --> Configuring: Reset
	TickProcess --> Configuring: Reset
	Paused --> Configuring: Reset

	note right of Configuring
		+Init
		#{ startTs } <= $startTs = _currentTimestamp()
		#{ hourAngle = 0, minuteAngle = 0, secondAngle = 0 }
	end note

	note right of TickProcess
		+ByPass
		#{ startTs } <= #startTs
		#{ secondAngle } <= mod(div(mult(diff(#startTs, _currentTimestamp()), 360), 1000000), 360)
		#{ minuteAngle } <= mod(div(mult(diff(#startTs, _currentTimestamp()), 360), 60000000), 360)
		#{ hourAngle } <= mod(div(mult(diff(#startTs, _currentTimestamp()), 360), 3600000000), 360)
	end note
