import { beforeEach, describe, expect, it, vitest } from 'vitest';
import { createEventBus } from '../src';
import { AbstractBaseClass } from '../src/mixins/BaseClass.js';
import { TTestEvent, TTestEventMeta } from './fixtures/index.js';

class EventBusTest extends createEventBus<
	TTestEvent,
	TTestEventMeta<TTestEvent>
>()(AbstractBaseClass) {

}

describe('eventBus', () => {
	let sampleInstance: EventBusTest = new EventBusTest();
	beforeEach(() => {
		vitest.restoreAllMocks();
		vitest.clearAllTimers();
		sampleInstance = new EventBusTest();
	});
	describe('constructor', () => {
		it('returns an instance of EventBusTest', () => {
			expect(sampleInstance).toBeInstanceOf(EventBusTest);
		});
		it('returns an instance of AbstractBaseClass', () => {
			expect(sampleInstance).toBeInstanceOf(AbstractBaseClass);
		});
		it('has an autogenerated alphanumeric Correlation ID', () => {
			expect(sampleInstance)
				.property('correlationId')
				.to
				.match(/^[A-Z0-9]+$/);
		});
		it('is empty by default', () => {
			expect(sampleInstance.getEventStack()).toEqual([]);
		});
	});
});
